fruits = []
i1 = input("Enter fruits name: ")
fruits.append(i1)
i2 = input("Enter fruits name: ")
fruits.append(i2)
i3 = input("Enter fruits name: ")
fruits.append(i3)
i4 = input("Enter fruits name: ")
fruits.append(i4)
i5 = input("Enter fruits name: ")
fruits.append(i5)
i6 = input("Enter fruits name: ")
fruits.append(i6)
i7 = input("Enter fruits name: ")
fruits.append(i7)
print(fruits)